# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  load_urls:
    cmd: stages/01_load_urls.sh
    deps:
      - stages/01_load_urls.sh
    outs:
      - raw
  download: 
    cmd: stages/02_download.sh
    deps:
      - stages/02_download.sh
      - raw
    outs:
      - pdfs
