stages:
  loadurls:
    cmd: python stages/01_get_openaccess.py
    deps:
    - stages/01_get_openaccess.py
    outs:
    - brick/articles.parquet:
        persist: true
  download:
    cmd: python stages/02_download.py
    deps:
    - brick/articles.parquet
    outs:
    - brick/downloads.parquet:
        persist: True
    - brick/pdfs:
        persist: True
