# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  status:
    cmd: python3 stages/00_status.py
  load_urls:
    cmd: stages/01_load_urls.sh
    deps:
      - stages/01_load_urls.sh
    outs:
      - raw:
         persist: true
  download: 
    cmd: stages/02_download.sh
    deps:
      - stages/02_download.sh
      - raw
    outs:
      - pdfs:
          persist: true
      - log.json
  check_pdfs:
    cmd: python3 stages/03_check_pdfs.py
    deps:
      - stages/03_check_pdfs.py
      - pdfs
      - log.json